ttc_saw_routing_groups = {
    
    'PSZSCZ': [
        'Closet Backing Panel', 
        'Garage Carcass Tall Back', 
        'Garage Carcass Upper Back',
        'Folding Station Riser',        
        'RPM|CTOP - Laminate',
        'Stainless Steel Countertop',
        'Plinth Face',
        'Matrix Bottom',
        'Drawer Box Bottom', 
        'Moovit Bottom',
        
    ],

    'PSZEBZSCZ': [
        'Closet Adjustable Shelf', 
        'Closet Hook Cleat', 
        'Closet Light Valance', 
        'Closet Top Shelf', 
        'Closet Upright Left No Drill', 
        'Garage Adjustable Shelf', 
        'HO Adjustable Shelf',
        'HO Murphy Queen Toe Kick',
        'HO Wallbed Door Slab',
        'HO Wallbed Subpanel', 
        'Laminate Countertop',
        'Melamine Countertop', 
        'Stock Fascia',
        'Trim for Crown',
        'Base Molding',
        'Applied Molding',
        'False Front Backer',
        'HO Murphy Full Toe Kick',
        'Moovit Filler',

    ],


    'PSZHDZSCZ': [     

    ],

    'PSZHDZPBZSCZ': [

    ],


    'PSZPRZPBZSCZ': [
        'Garage Carcass Base Back', 
        'Garage Carcass Notch Back', 
        'Garage Nailer Bottom', 
        'Garage Nailer Middle', 
        'Garage Nailer Top', 
        'HO Carcass Base Back',
        'HO Carcass Tall Back', 
        'HO Carcass Upper Back',
    ],

    'PSZHRZSCZ': [        
        'Island Backing Panel',
        'Closet Corner Fixed Shelf',

    ],

    'PSZPRZSCZ': [
        'Closet Toe Kick',
        'HO Base Toekick',
        'HO Tall Toekick',
    ],

    'PSZHRZEBZSCZ': [
        'Closet Adjustable Shelf Safety',
        'Closet Bridge Fixed Shelf',
        'Closet Corner Adjustable Shelf Safety', 
        'Closet Door Slab',
        'Closet Drawer Front Slab', 
        'Closet Elite Shoe Shelf', 
        'Closet Filler', 
        'Closet Fixed Shelf', 
        'Closet Nailer', 
        'Closet Top Shelf LED',
        'Closet Upright Hanging Radius Thru', 
        'Closet Upright Hanging Square Left', 
        'Closet Upright Hanging Square Right', 
        'Closet Upright Hanging Square Thru', 
        'Closet Upright LED Left', 
        'Closet Upright LED Right', 
        'Closet Upright LED Thru', 
        'Closet Upright Left', 
        'Closet Upright Right', 
        'Closet Upright Thru', 
        'Closet Upright Transition Left',
        'Closet Upright Transition Right',
        'Garage Fixed Shelf',         
        'Garage Tall Divider', 
        'HO Carcass Base Bottom', 
        'HO Carcass Base Left', 
        'HO Carcass Base Right', 
        'HO Carcass Base Top',
        'HO Carcass Tall Left',
        'HO Carcass Tall Right',
        'HO Carcass Tall Top',
        'HO Carcass Tall Bottom', 
        'HO Carcass Upper Bottom', 
        'HO Carcass Upper Left', 
        'HO Carcass Upper Right', 
        'HO Carcass Upper Top',
        'HO Fixed Shelf',
        'HO Murphy Queen Left Side',
        'HO Murphy Queen Right Side',
        'HO Murphy Queen Top',
        'HO Murphy Queen Headboard',
        'HO Murphy Queen Nailer Top',
        'HO Murphy Queen Bottom Stretcher',
        'Island Panel End',
        'Island Panel Thru',
        'Closet Upright Bottom Stacking Left',
        'Closet Upright Bottom Stacking LED Left',
        'Closet Upright Top Stacking LED Left',
        'Closet Upright Bottom Stacking Right',
        'Closet Upright Bottom Stacking LED Right',
        'Closet Upright Top Stacking LED Right',
        'Closet Upright Bottom Stacking Thru',
        'Closet Upright Top Stacking LED Thru',
        'Closet Upright Bottom Stacking LED Thru',
        'Bottom Cubbie Fixed Shelf',
        'Top Cubbie Fixed Shelf',
        'Closet Upright Cubbie Divider Thru',
        'Closet Upright Hutch Panel Left',
        'Closet Upright Hutch Panel Right',
        'Closet Upright Top Stacking Thru',
        'Closet Upright Top Stacking Right',
        'Closet Upright Top Stacking Left',
        'Closet Upright Hanging Radius Left',
        'HO Tall Divider',
        'Garage Base Divider',
        'Garage Carcass Base Bottom', 
        'Garage Carcass Base Left', 
        'Garage Carcass Base Right', 
        'Garage Carcass Base Top', 
        'Garage Carcass Notch Top', 
        'Garage Carcass Tall Bottom', 
        'Garage Carcass Tall Left', 
        'Garage Carcass Tall Right', 
        'Garage Carcass Tall Top', 
        'Garage Carcass Upper Bottom', 
        'Garage Carcass Upper Left', 
        'Garage Carcass Upper Right', 
        'Garage Carcass Upper Top',
        'Closet Upright Basenotch Thru',
        'Matrix Back',
        'Matrix Bottom Drawer Front',
        'Matrix Drawer Front',
        'Closet Upright Hanging Radius Right',
        'Closet Upright Bottom Stacking Transition Left',
        'Closet Upright Top Stacking Transition Left',   
        'Closet Upright LED Left No Drill', 
        'HO Upper Divider', 
        'Drawer Box Back', 
        'Drawer Box Front', 
        'Drawer Box Left Side', 
        'Drawer Box Right Side',
        'Closet Corner Adjustable Shelf',
        'HO Murphy Full Left Side',
        'HO Murphy Full Right Side',
        'HO Murphy Full Top',
        'HO Murphy Full Headboard',
        'HO Murphy Full Nailer Top',
        'HO Murphy Full Bottom Stretcher',
        'Suspended Drawer Left Side',
        'Suspended Drawer Right Side',
        'Suspended Drawer Top Front Nailer',
        'Suspended Drawer Rear Nailer',
        'Suspended Drawer Top Rear Nailer',
        'HO Adjustable Shelf Safety',
        'Closet Upright Basenotch Right',
        'Closet Upright Basenotch Left',
        'HO LED Fixed Shelf',
        'Closet Upright Right No Drill',
    ],


    'PSZHRZPRZEBZSCZ': [
              
    ],
    
    'NMZ': [
        'Drawer Box Back', 
        'Drawer Box Bottom', 
        'Drawer Box Front', 
        'Drawer Box Left Side', 
        'Drawer Box Right Side',
    ]
}

ttc_nested_routing_groups = {
    
    'TRZSCZ': [
        'Closet Backing Panel', 
        'Garage Carcass Tall Back', 
        'Garage Carcass Upper Back',
        'Folding Station Riser',        
        'RPM|CTOP - Laminate',
    ],

    'TRZEBZSCZ': [
        'Closet Adjustable Shelf',
        'Closet Adjustable Shelf Safety',
        'Closet Bridge Fixed Shelf', 
        'Closet Door Slab',
        'Closet Drawer Front Slab', 
        'Closet Elite Shoe Shelf', 
        'Closet Filler', 
        'Closet Fixed Shelf',  
        'Closet Hook Cleat', 
        'Closet Light Valance', 
        'Closet Nailer', 
        'Closet Top Shelf', 
        'Closet Top Shelf LED',        
        'Closet Upright Hanging Radius Thru', 
        'Closet Upright Hanging Square Left', 
        'Closet Upright Hanging Square Right', 
        'Closet Upright Hanging Square Thru', 
        'Closet Upright LED Left', 
        'Closet Upright LED Right', 
        'Closet Upright Left',
        'Closet Upright Left No Drill', 
        'Closet Upright Right', 
        'Closet Upright Thru', 
        'Closet Upright Transition Left',
        'Closet Upright Transition Right',      
        'Garage Adjustable Shelf', 
        'HO Adjustable Shelf', 
        'Laminate Countertop',
        'Melamine Countertop', 
        'Stock Fascia',
        'Trim for Crown',
        'Closet Upright Bottom Stacking Left',
        'Closet Upright Bottom Stacking LED Left',
        'Closet Upright Top Stacking LED Left',
        'Closet Upright Bottom Stacking Right',
        'Closet Upright Bottom Stacking LED Right',
        'Closet Upright Top Stacking LED Right',
        'Closet Upright Bottom Stacking Thru',
        'Closet Upright Top Stacking LED Thru',
        'Closet Upright Bottom Stacking LED Thru',
        'Bottom Cubbie Fixed Shelf',
        'Top Cubbie Fixed Shelf',
        'Closet Upright Cubbie Divider Thru',
        'Closet Upright Hutch Panel Left',
        'Closet Upright Hutch Panel Right',

        
    ],

    'TRZHDZSCZ': [
        'HO Base Toekick'
    ],

    'TRZHDZPBZSCZ': [
        'Garage Carcass Base Back', 
        'Garage Carcass Notch Back', 
        'Garage Nailer Bottom', 
        'Garage Nailer Middle', 
        'Garage Nailer Top', 
        'HO Carcass Base Back', 
        'HO Carcass Upper Back' 
    ],

    'TRZHRZSCZ': [
        'Closet Toe Kick'
    ],

    'TRZHRZEBZSCZ': [               
        'Garage Tall Divider', 
        'HO Carcass Base Bottom', 
        'HO Carcass Base Left', 
        'HO Carcass Base Right', 
        'HO Carcass Base Top', 
        'HO Carcass Upper Bottom', 
        'HO Carcass Upper Left', 
        'HO Carcass Upper Right', 
        'HO Carcass Upper Top',        
    ],

    'TRZHRZPRZEBZSCZ': [
        'Garage Carcass Base Bottom', 
        'Garage Carcass Base Left', 
        'Garage Carcass Base Right', 
        'Garage Carcass Base Top', 
        'Garage Carcass Notch Top', 
        'Garage Carcass Tall Bottom', 
        'Garage Carcass Tall Left', 
        'Garage Carcass Tall Right', 
        'Garage Carcass Tall Top', 
        'Garage Carcass Upper Bottom', 
        'Garage Carcass Upper Left', 
        'Garage Carcass Upper Right', 
        'Garage Carcass Upper Top',        
    ],
    
    'NMZ': [
        'Drawer Box Back', 
        'Drawer Box Bottom', 
        'Drawer Box Front', 
        'Drawer Box Left Side', 
        'Drawer Box Right Side'
    ]
}
