name: Lines of Code Analysis with Visual Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  loc-visual:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate LOC and Language Breakdown
        uses: srt32/linguist-loc@v1
        id: loc

      - name: Output Visual Report
        run: |
          echo "Language Breakdown"
          echo "${{ steps.loc.outputs.report }}"
